apiVersion: v1
kind: Service
metadata:
  name: gochina-agent
  namespace: default
spec:
  selector:
    app: gochina-agent
  ports:
    - protocol: TCP
      port: 8787
      targetPort: 8787
  type: ClusterIP
