/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesVisaRouteImport } from './routes/guides.visa'
import { Route as GuidesTransitRouteImport } from './routes/guides.transit'
import { Route as GuidesFoodRouteImport } from './routes/guides.food'
import { Route as GuidesEtiquetteRouteImport } from './routes/guides.etiquette'
import { Route as GuidesDigitalRouteImport } from './routes/guides.digital'
import { Route as GuidesAirRouteImport } from './routes/guides.air'
import { Route as ExploreCategoryRouteImport } from './routes/explore.$category'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesVisaRoute = GuidesVisaRouteImport.update({
  id: '/guides/visa',
  path: '/guides/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesTransitRoute = GuidesTransitRouteImport.update({
  id: '/guides/transit',
  path: '/guides/transit',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesFoodRoute = GuidesFoodRouteImport.update({
  id: '/guides/food',
  path: '/guides/food',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesEtiquetteRoute = GuidesEtiquetteRouteImport.update({
  id: '/guides/etiquette',
  path: '/guides/etiquette',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesDigitalRoute = GuidesDigitalRouteImport.update({
  id: '/guides/digital',
  path: '/guides/digital',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesAirRoute = GuidesAirRouteImport.update({
  id: '/guides/air',
  path: '/guides/air',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCategoryRoute = ExploreCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ExploreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/itinerary': typeof ItineraryRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/explore/$category': typeof ExploreCategoryRoute
  '/guides/air': typeof GuidesAirRoute
  '/guides/digital': typeof GuidesDigitalRoute
  '/guides/etiquette': typeof GuidesEtiquetteRoute
  '/guides/food': typeof GuidesFoodRoute
  '/guides/transit': typeof GuidesTransitRoute
  '/guides/visa': typeof GuidesVisaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/itinerary': typeof ItineraryRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/explore/$category': typeof ExploreCategoryRoute
  '/guides/air': typeof GuidesAirRoute
  '/guides/digital': typeof GuidesDigitalRoute
  '/guides/etiquette': typeof GuidesEtiquetteRoute
  '/guides/food': typeof GuidesFoodRoute
  '/guides/transit': typeof GuidesTransitRoute
  '/guides/visa': typeof GuidesVisaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/itinerary': typeof ItineraryRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/explore/$category': typeof ExploreCategoryRoute
  '/guides/air': typeof GuidesAirRoute
  '/guides/digital': typeof GuidesDigitalRoute
  '/guides/etiquette': typeof GuidesEtiquetteRoute
  '/guides/food': typeof GuidesFoodRoute
  '/guides/transit': typeof GuidesTransitRoute
  '/guides/visa': typeof GuidesVisaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/itinerary'
    | '/onboarding'
    | '/profile'
    | '/explore/$category'
    | '/guides/air'
    | '/guides/digital'
    | '/guides/etiquette'
    | '/guides/food'
    | '/guides/transit'
    | '/guides/visa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/itinerary'
    | '/onboarding'
    | '/profile'
    | '/explore/$category'
    | '/guides/air'
    | '/guides/digital'
    | '/guides/etiquette'
    | '/guides/food'
    | '/guides/transit'
    | '/guides/visa'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/itinerary'
    | '/onboarding'
    | '/profile'
    | '/explore/$category'
    | '/guides/air'
    | '/guides/digital'
    | '/guides/etiquette'
    | '/guides/food'
    | '/guides/transit'
    | '/guides/visa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  ItineraryRoute: typeof ItineraryRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  GuidesAirRoute: typeof GuidesAirRoute
  GuidesDigitalRoute: typeof GuidesDigitalRoute
  GuidesEtiquetteRoute: typeof GuidesEtiquetteRoute
  GuidesFoodRoute: typeof GuidesFoodRoute
  GuidesTransitRoute: typeof GuidesTransitRoute
  GuidesVisaRoute: typeof GuidesVisaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/visa': {
      id: '/guides/visa'
      path: '/guides/visa'
      fullPath: '/guides/visa'
      preLoaderRoute: typeof GuidesVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/transit': {
      id: '/guides/transit'
      path: '/guides/transit'
      fullPath: '/guides/transit'
      preLoaderRoute: typeof GuidesTransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/food': {
      id: '/guides/food'
      path: '/guides/food'
      fullPath: '/guides/food'
      preLoaderRoute: typeof GuidesFoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/etiquette': {
      id: '/guides/etiquette'
      path: '/guides/etiquette'
      fullPath: '/guides/etiquette'
      preLoaderRoute: typeof GuidesEtiquetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/digital': {
      id: '/guides/digital'
      path: '/guides/digital'
      fullPath: '/guides/digital'
      preLoaderRoute: typeof GuidesDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/air': {
      id: '/guides/air'
      path: '/guides/air'
      fullPath: '/guides/air'
      preLoaderRoute: typeof GuidesAirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$category': {
      id: '/explore/$category'
      path: '/$category'
      fullPath: '/explore/$category'
      preLoaderRoute: typeof ExploreCategoryRouteImport
      parentRoute: typeof ExploreRoute
    }
  }
}

interface ExploreRouteChildren {
  ExploreCategoryRoute: typeof ExploreCategoryRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreCategoryRoute: ExploreCategoryRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRouteWithChildren,
  ItineraryRoute: ItineraryRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  GuidesAirRoute: GuidesAirRoute,
  GuidesDigitalRoute: GuidesDigitalRoute,
  GuidesEtiquetteRoute: GuidesEtiquetteRoute,
  GuidesFoodRoute: GuidesFoodRoute,
  GuidesTransitRoute: GuidesTransitRoute,
  GuidesVisaRoute: GuidesVisaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
